### PR TITLE
The typescript callback format was wrong 

### PR DESCRIPTION
**Pull request by saulogt**

### CODE REVIEW

**Comment by philosoralphter** [comment]
Thanks @saulogt, taking a look.  

@joelday , do you want to confirm this change?  You are the one who wrote the ts stuff, so just want to make sure this is in line with your intended use, etc.

**Comment by philosoralphter** [comment]
@saulogt is there some reason you do not want to pass the response to the callback?  The response to a track request could contain js trigger code to run...

**Comment by philosoralphter** [comment]
ah i see, we are already returning error and code only.

**Comment by saulogt** [comment]
It's just to reflect the actual behaviour

**Comment by joelday** [comment]
Yup. If those two arguments are what goes into the callback, then that's what the signature should be.

**Comment by philosoralphter** [comment]
right.  ok i think i'm going to update this to return the http.IncomingMessage.  I want the server to be able to take the body and run the code if desired on the browser, and to see any errors in the body as well, etc.  I'll make it a major upgrade version in npm.  please look for that within the day.  I Will start by merging this though.  Thanks to you both

**Comment by saulogt** [comment]
Will you release I minor version with this no-breaking change to npm too?

**Comment by philosoralphter** [comment]
Would you two take a look at the changes here: to make sure I did the typescript part correctly, and to see what you think about the change?  thanks!! (also feel free to add names in contributors in package.json)

https://github.com/Woopra/node-woopra/tree/pass-track-response

**Comment by philosoralphter** [comment]
@saulogt: done. it's v0.4.0

1.0.0 will begin to return the response itself.

**Comment by saulogt** [comment]
Thanks.
The new callback returning IncomingMessage looks good

**Comment by saulogt** [comment]
The Readme.md should reflect the change.
This is not good anymore:
```
woopra.track('eventName', {
    eventProperty: 'property'
}, function(err, responseCode) {
	if(err) throw err;
	console.log(responseCode); //200 if OK
});
```

**Comment by philosoralphter** [comment]
oh good catch! thanks!!

**Pull request merged**
